environments:
  - type: 1  
    aem_hosts: 
      eng: 4502
      test: 4503
      prod: 4505
  - type: 2 
    aem_hosts:
      eng: 5502
      test: 5503
      prod: 5505
  - type: 3
    aem_hosts:
      eng: 6502
      localhost:4502
      prod: 6505
